// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dante Doménech Martinez dante19031999@gmail.com

#![cfg(feature = "loki")]
#![cfg_attr(docsrs, doc(cfg(feature = "loki")))]

use crate::service::{HttpError, LokiConfig, ServiceError};
use crate::{LoggerImpl, LoggerStatus, Message};
use chrono::{SecondsFormat, Utc};
use reqwest::blocking::{Client, RequestBuilder, Response};
use serde_json::json;
use std::any::Any;
use std::ops::AddAssign;
use std::sync::mpsc::{Receiver, Sender};
use std::sync::{Arc, Mutex};
use std::thread;
use std::thread::JoinHandle;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

/// A container for a log message and its assigned metadata.
///
/// This struct pairs a generic [`Message`] with a specific [`SystemTime`]
/// generated by the logger's monotonic highwater system. This ensures that
/// even if multiple messages are generated in the same microsecond, they
/// maintain a strictly increasing order for Loki.
pub struct LokiMessage {
    /// The original log content and level.
    pub message: Message,
    /// The unique, strictly increasing timestamp for this specific entry.
    pub timestamp: SystemTime,
}

/// Shared state and configuration for the Loki service.
///
/// This struct is typically wrapped in an [`Arc`] to be shared between the
/// frontend logger and the background worker thread.
pub struct LokiData {
    /// The pre-configured HTTP client (handles connection pooling).
    pub client: Client,
    /// User-defined configuration (retries, timeouts, labels).
    pub config: LokiConfig,
    /// The full computed URL (e.g., `http://host:port/loki/api/v1/push`).
    pub post_url: String,
}

/// The core logic provider for Loki interactions.
///
/// This trait defines how batches of logs are collected, formatted, and pushed.
/// By implementing this trait, you can customize the batching strategy or
/// adding custom logic (like GZIP compression) before sending.
///
/// ### Required Hierarchy
/// Must implement [`LokiFallback`] to handle delivery failures.
pub trait LokiService: LokiFallback {
    /// Orchestrates the background worker loop.
    ///
    /// This method is the entry point for the worker thread. It implements a
    /// **double-buffer/drain** strategy:
    /// 1. It blocks on `receiver.recv()` until at least one message is available,
    ///    ensuring zero CPU usage during idle periods.
    /// 2. Once a message arrives, it performs a non-blocking `try_recv` loop to
    ///    "drain" the channel and form a batch.
    /// 3. It groups messages by their log level into a `BTreeMap` to maintain
    ///    consistent stream ordering before calling [`work_batch`][`Self::work_batch()`].
    ///
    /// This design assumes that network I/O is the bottleneck, allowing the
    /// in-memory collection of logs to be extremely fast.
    fn work(&self, receiver: Receiver<LokiMessage>, data: Arc<LokiData>) {
        let mut messages = std::collections::BTreeMap::<String, Vec<LokiMessage>>::new();

        // Get first message
        while let Ok(message) = receiver.recv() {
            // Deal with message
            let level = message.message.level().to_string();
            messages.entry(level).or_insert_with(Vec::new).push(message);

            // Get batch
            while let Ok(message) = receiver.try_recv() {
                let level = message.message.level().to_string();
                messages.entry(level).or_insert_with(Vec::new).push(message);
            }

            // Process batch
            for (level, batch) in &mut messages {
                if !batch.is_empty() {
                    let _ = self.work_batch(level, batch, &data);
                }
            } // Process batch
        } // Receive message
    }

    /// Handles the transformation and transmission of a specific log batch.
    ///
    /// This method performs the following steps:
    /// 1. **Serialization**: Converts the batch of [`LokiMessage`] into a
    ///    JSON payload compatible with the Loki Push API.
    /// 2. **Transmission**: Sends the payload via a POST request.
    /// 3. **Retry Logic**: If the request fails or returns a non-success status,
    ///    it enters a retry loop up to the `max_retries` limit defined in [`LokiConfig`].
    /// 4. **Safety Net**: If all retries fail, it triggers the [`LokiFallback`]
    ///    mechanism for every message in the batch.
    /// 5. **Cleanup**: Clears the batch vector to prepare it for the next iteration,
    ///    reusing the allocated memory capacity.
    ///
    /// # Returns
    ///
    /// Returns the last [`Response`] received from the server, or a [`ServiceError`]
    /// if the transmission was impossible.
    fn work_batch(
        &self,
        level: &str,
        batch: &mut Vec<LokiMessage>,
        data: &Arc<LokiData>,
    ) -> Result<Response, ServiceError> {
        // Prepare messages for loki
        let payload_batch = batch
            .iter()
            .map(|message| {
                let timestamp = message
                    .timestamp
                    .duration_since(UNIX_EPOCH)
                    .expect("Time went backwards")
                    .as_nanos();
                json!([timestamp.to_string(), message.message.content().to_string()])
            })
            .collect::<Vec<_>>();

        // Payload
        let payload = json!({
            "streams": [{
                "stream": {
                    "app": data.config.get_app(),
                    "job": data.config.get_job(),
                    "env": data.config.get_env(),
                    "level": level,
                },
                "values": payload_batch
            }]
        });

        // First attempt
        let txt_payload = payload.to_string();
        let mut response = LokiLogger::request_post(txt_payload, &data);

        // Check if retry
        let needs_retry = match &response {
            Ok(response) => !response.status().is_success(),
            Err(_) => true,
        };

        // Attempt until end of lives
        if needs_retry {
            let mut i = 0usize;
            let payload = payload.to_string();

            response = loop {
                let current_response = LokiLogger::request_post(payload.clone(), &data);

                // Check if retry
                let is_success = match &current_response {
                    Ok(current_response) => current_response.status().is_success(),
                    Err(_) => false,
                };

                // End if retry
                if is_success {
                    break current_response;
                }

                if i >= data.config.get_max_retries() {
                    match current_response {
                        Ok(current_response) => {
                            break Err(ServiceError::Http(HttpError::new(
                                current_response.status().as_u16(),
                            )));
                        }
                        Err(_) => {
                            break current_response;
                        }
                    }
                }

                i += 1;
            } // Loop
        } // If not first OK

        // Last fallback
        if let Err(error) = &response {
            for message in &*batch {
                self.fallback(error, &message.message);
            }
        }

        // Clear message trail
        batch.clear();

        response
    }
}

/// A resilience strategy for handling Loki delivery failures.
///
/// [`LokiFallback`] provides a "last-resort" mechanism to prevent data loss when
/// the background worker cannot deliver logs to the remote server.
///
/// ### Hierarchy
/// This trait is a super-trait of [`LokiService`]. Every service must define
/// what happens when the primary transport (HTTP) fails.
pub trait LokiFallback {
    /// Handles the ultimate delivery failure for a log message.
    ///
    /// This method is the "safety net" of the logging pipeline. It is invoked when
    /// a message cannot be sent to Loki after exhausting all retry attempts or
    /// encountering a non-recoverable error (like a 400 Bad Request).
    ///
    /// ### Default Behavior
    /// The default implementation performs a **Best-Effort** recovery:
    /// 1. Formats the failure reason (HTTP status or Network error) to `stderr`.
    /// 2. Prints the original log content to `stdout` with its timestamp,
    ///    level, and payload.
    ///
    /// This ensures that even in a total network collapse, the logs are
    /// captured by the system's standard output streams (useful for Docker/K8s
    /// logs collectors).
    ///
    /// ### Thread Safety
    /// This is called from the background worker thread. Any custom implementation
    /// must be non-blocking and thread-safe to avoid stalling the entire
    /// logging pipeline.
    fn fallback(&self, error: &ServiceError, msg: &Message) {
        let now: chrono::DateTime<Utc> = msg.instant().into();
        let now = now.to_rfc3339_opts(SecondsFormat::Nanos, true);

        match error {
            ServiceError::Http(e) => eprintln!("Loki rejected log: Status {}", e.status_code()),
            ServiceError::Network(e) => eprintln!("Loki network error: {}", e),
            _ => eprintln!("Loki service failure: {}", error),
        }

        println!("{} [{}] | {}", now, msg.level(), msg.content());
    }
}

/// The standard implementation of the Loki transport logic.
///
/// [`DefaultLokiService`] provides the baseline behavior for the logging pipeline,
/// using the standard batching and retry mechanisms defined in the [`LokiService`]
/// default trait methods.
///
/// ### Behavior
/// - **Transport**: Uses the `reqwest` blocking client to push JSON payloads.
/// - **Fallback**: Inherits the default [`LokiFallback`] behavior, which redirects
///   failed logs to the system's standard error and output streams.
///
/// This struct is stateless, acting primarily as a marker to satisfy the trait
/// requirements of the [`LokiLogger`].
pub struct DefaultLokiService {}

impl LokiService for DefaultLokiService {}

impl LokiFallback for DefaultLokiService {}

/// A persistent, asynchronous logger implementation for Grafana Loki.
///
/// `LokiLogger` manages a dedicated background worker thread that handles batching,
/// retries, and HTTP transmission. It is designed to be high-performance, ensuring
/// that the main application thread is never blocked by network latency.
///
/// ### Important Design Notes
/// - **Monotonic Dating**: This logger uses an internal "highwater" marking system.
///   The original date of the `Message` is ignored in favor of a strictly increasing
///   timestamp generated at the moment of dispatch. This prevents Loki from rejecting
///   out-of-order logs during high-frequency bursts.
/// - **Worker Lifecycle**: A background thread is spawned on creation. Logs are
///   transmitted via an MPSC channel. Dropping the logger will signal the worker
///   to finish pending tasks before shutting down.
/// - **Performance**: Internal operations (batching, grouping by level) are performed
///   in-memory, assuming that network I/O is the primary bottleneck.
pub struct LokiLogger {
    highwater: Mutex<SystemTime>,
    worker: Option<JoinHandle<()>>,
    sender: Option<Sender<LokiMessage>>,
    data: Arc<LokiData>,
    service: Arc<dyn LokiService + Send + Sync>,
}

impl LokiLogger {
    /// Creates a new `LokiLogger` using the [`DefaultLokiService`].
    ///
    /// This is a convenience wrapper around [`Self::with_service`].
    pub fn new(config: LokiConfig) -> Box<LokiLogger> {
        Self::with_service(config, Box::new(DefaultLokiService {}))
    }

    /// Primary constructor that initializes the logger with a custom [`LokiService`].
    ///
    /// This method:
    /// 1. Computes the full Loki Push API endpoint.
    /// 2. Wraps the provided service in an [`Arc`] for shared access between the logger and the worker.
    /// 3. Spawns a background worker thread to process the log queue.
    ///
    /// ### Dependency Injection
    /// By providing a custom [`LokiService`], you can override how batches are processed,
    /// enabling features like compression, custom filtering, or specialized error handling.
    ///
    /// # Threading
    /// Spawns a dedicated OS thread. The worker handles all network I/O and will
    /// gracefully shut down when the `LokiLogger` instance is dropped.
    ///
    /// # Panics
    /// Panics if the internal [`Client`][reqwest::blocking::Client] cannot be initialized.
    pub fn with_service(
        config: LokiConfig,
        service: Box<dyn LokiService + Send + Sync>,
    ) -> Box<LokiLogger> {
        let mut post_url = config.url.clone();
        post_url.push_str("loki/api/v1/push");

        // Loki data
        let data = Arc::new(LokiData {
            client: Self::build_client(&config),
            config,
            post_url,
        });

        let work_data = data.clone();
        let service: Arc<dyn LokiService + Send + Sync> = Arc::from(service);
        let work_service = service.clone();
        let (sender, receiver) = std::sync::mpsc::channel::<LokiMessage>();

        Box::new(LokiLogger {
            highwater: Mutex::new(SystemTime::now()),
            worker: Some(thread::spawn(move || {
                work_service.work(receiver, work_data)
            })),
            sender: Some(sender),
            data,
            service,
        })
    }

    /// Constructs a pre-configured HTTP client for the Loki service.
    ///
    /// This client is built with the specific connection and request timeouts
    /// defined in the [`LokiConfig`]. It is intended to be used within an [`Arc`]
    /// to share a connection pool across the worker's lifecycle.
    ///
    /// # Panics
    /// - Panics if the TLS backend cannot be initialized or if the system
    /// configuration prevents creating a secure socket.
    pub fn build_client(config: &LokiConfig) -> Client {
        Client::builder()
            .connect_timeout(config.connection_timeout)
            .timeout(config.request_timeout)
            .build()
            .expect("Failed to build reqwest client")
    }

    /// Performs a synchronous POST request to the Loki push API.
    ///
    /// This method handles the low-level HTTP transmission, including setting
    /// the `Content-Type` header and attaching authentication credentials.
    ///
    /// # Errors
    /// Returns a [`ServiceError::Network`] if the server is unreachable,
    /// DNS resolution fails, or the connection times out.
    pub fn request_post(payload: String, data: &Arc<LokiData>) -> Result<Response, ServiceError> {
        let mut request = data
            .client
            .post(data.post_url.as_str())
            .header("Content-Type", "application/json")
            .body(payload); // payload is already a String, no need for .to_string()

        request = LokiLogger::request_auth(request, &data);

        request.send().map_err(ServiceError::Network)
    }

    /// Decorates a [`RequestBuilder`] with the configured authentication method.
    ///
    /// Supports both **Basic Auth** (username/password) and **Bearer Token** /// authentication. If both are configured, they will both be applied to
    /// the request (though Loki usually expects only one).
    ///
    /// # Parameters
    /// - `request`: The initial request builder to decorate.
    /// - `data`: The shared data containing authentication credentials.
    pub fn request_auth(mut request: RequestBuilder, data: &Arc<LokiData>) -> RequestBuilder {
        if let Some(auth) = &data.config.basic_auth {
            request = request.basic_auth(&auth.username, auth.password.as_deref());
        }
        if let Some(token) = &data.config.bearer_auth {
            request = request.bearer_auth(token);
        }
        request
    }
}

impl LoggerImpl for LokiLogger {
    /// Returns the current operational status of the Loki service.
    ///
    /// This method performs a live health check by hitting the `/loki/status` endpoint.
    /// It uses a functional pipeline to transform the network result into a [`LoggerStatus`].
    ///
    /// ### Performance Note:
    /// This call is **blocking**. If the network is slow or the Loki server is hanging,
    /// this method will block the calling thread until the default timeout is reached.
    ///
    /// # Returns
    /// * [`LoggerStatus::Running`] - Server is reachable and returned a success code.
    /// * [`LoggerStatus::Broken`] - Any failure occurred (DNS, Connection Refused, 404, 500, etc.).
    fn status(&self) -> LoggerStatus {
        // Fetch url
        let mut url = self.data.config.url.clone();
        url.push_str("ready");

        // Build request
        let mut request = self.data.client.get(&url);
        request = Self::request_auth(request, &self.data);

        // Perform request
        request
            .send()
            .ok()
            .map(|response| match response.status().is_success() {
                true => LoggerStatus::Running,
                false => LoggerStatus::Broken,
            })
            .unwrap_or(LoggerStatus::Broken)
    }

    /// Enqueues a [`Message`] for asynchronous processing and delivery.
    ///
    /// This is the primary entry point for recording logs. It performs two critical tasks:
    /// 1. **Monotonic Timestamping**: Uses a "highwater" Mutex to ensure every message
    ///    has a strictly increasing timestamp, preventing Loki out-of-order errors.
    /// 2. **Asynchronous Dispatch**: Sends the message through an MPSC channel to the
    ///    background worker.
    ///
    /// ### Thread Safety & Performance
    /// This method is non-blocking (except for a very brief lock on the highwater
    /// timestamp). If the background worker is overloaded or the channel is
    /// disconnected, it triggers the [`LokiFallback`] immediately to avoid data loss.
    ///
    /// # Parameters
    /// - `message`: The log entry containing level, target, and content.
    fn log(&self, message: Message) {
        // Process highwater
        let mut timestamp = SystemTime::now();
        if let Ok(mut highwater) = self.highwater.lock() {
            if timestamp <= *highwater {
                highwater.add_assign(Duration::new(0, 1));
                timestamp = *highwater
            }
        }

        // Add to queue
        if let Some(sender) = &self.sender {
            if let Err(error) = sender.send(LokiMessage { timestamp, message }) {
                let message = error.0;
                self.service
                    .fallback(&ServiceError::LockPoisoned, &message.message);
            }
        } else {
            self.service.fallback(&ServiceError::LockPoisoned, &message);
        }
    }

    /// Returns a reference to the underlying type as [Any] for downcasting.
    fn as_any(&self) -> &dyn Any {
        self
    }
}

/// Ensures a graceful shutdown of the logging pipeline.
///
/// When the `LokiLogger` goes out of scope, the following sequence occurs:
/// 1. **Channel Closure**: The `sender` is dropped (`None`). This signals the background
///    worker that no more messages will be sent.
/// 2. **Worker Drain**: The worker's `receiver.recv()` will return an error once
///    the channel is empty, allowing its loop to terminate naturally.
/// 3. **Thread Join**: The main thread blocks until the worker thread has finished
///    processing and sending the final batch of logs.
///
/// This mechanism prevents data loss during application shutdown or restarts.
impl Drop for LokiLogger {
    fn drop(&mut self) {
        // Drop the sender first to close the MPSC channel
        self.sender = None;

        // Wait for the worker thread to finish its last batch
        if let Some(worker) = self.worker.take() {
            let _ = worker.join();
        }
    }
}
