// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dante Doménech Martinez dante19031999@gmail.com

#![cfg(feature = "loki")]
#![cfg_attr(docsrs, doc(cfg(feature = "loki")))]

use std::time::SystemTime;

/// A container for a log message and its assigned metadata.
///
/// This struct pairs a generic [`Message`][`crate::Message`] with a specific [`SystemTime`]
/// generated by the logger's monotonic highwater system. This ensures that
/// even if multiple messages are generated in the same microsecond, they
/// maintain a strictly increasing order for Loki.
pub struct Message {
    /// The original log content and level.
    pub message: crate::Message,
    /// The unique, strictly increasing timestamp for this specific entry.
    pub timestamp: SystemTime,
}
